services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/passport/vaultwarden/library:/data/
    networks:
      - vaultwarden_network
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.5'
        reservations:
          memory: 64m
          cpus: '0.05'

networks:
  vaultwarden_network:
    name: vaultwarden_default
    driver: bridge
