services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./vw-data/:/data/
    networks:
      - vaultwarden_network

networks:
  vaultwarden_network:
    name: vaultwarden_default
    driver: bridge