services:
  server:
    image: codeberg.org/forgejo/forgejo:15.0.1
    container_name: forgejo
    restart: unless-stopped
    networks:
      - forgejo_network
    volumes:
      - ./forgejo_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 222:22
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '2'
        reservations:
          memory: 128m
          cpus: '0.1'

  db:
    image: postgres:14
    container_name: forgejo_postgres
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - forgejo_network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    deploy:
        resources:
          limits:
            memory: 512m
            cpus: '1'
          reservations:
            memory: 128m
            cpus: '0.1'

networks:
  forgejo_network:
    name: forgejo_default
    driver: bridge

volumes:
  forgejo_data:
  postgres_data: