services:
  server:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    restart: always
    networks:
      - forgejo_network
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8950:3000
      - 222:22
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '1'
        reservations:
          memory: 128m
          cpus: '0.1'

networks:
  forgejo_network:
    name: forgejo_default
    driver: bridge
