services:
  app:
    image: nextcloud
    container_name: nextcloud-compose
    restart: unless-stopped
    depends_on:
      - redis
      - db
    volumes:
      - ${NEXTCLOUD_LIBRARY}:/var/www/html
      - ./.nextcloud_config/local_access.config.php:/var/www/html/config/local_access.config.php:ro
    environment:
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS={nextcloud.tail.sargun.ca}
      - TRUSTED_DOMAINS={nextcloud.tail.sargun.ca}
      - OVERWRITECLIURL=https://nextcloud.tail.sargun.ca
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_DEFAULT_PHONE_REGION=US
    networks:
      - nextcloud_network
      - authentik_network
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '2'
        reservations:
          memory: 256m
          cpus: '0.25'

  db:
    image: mariadb:lts
    container_name: nextcloud-compose-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}
    networks:
      - nextcloud_network
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '1'
        reservations:
          memory: 256m
          cpus: '0.25'

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud_network
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.5'
        reservations:
          memory: 16m
          cpus: '0.1'

  collabora:
    image: collabora/code
    container_name: collabora
    environment:
      - aliasgroup1=${alias11}
      - DONT_GEN_SSL_CERT=YES
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - username=${COLLABORA_USER}
      - password=${COLLABORA_PASSWORD}
    cap_add:
      - MKNOD
      - SYS_ADMIN
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9980/hosting/discovery"]
    networks:
      - nextcloud_network
    deploy:
      resources:
        limits:
          memory: 3g
          cpus: '3'
        reservations:
          memory: 512m
          cpus: '0.25'

networks:
  nextcloud_network:
    name: nextcloud_default
    driver: bridge
  authentik_network:
    external: true
    name: authentik_default
