services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: '0.25'
        reservations:
          memory: 16m
          cpus: '0.05'